export enum Name {
  Male = 'Male',
  Female = 'Female',
  Type1 = 'TypeOne',
  Type2 = 'TypeTwo',
  Risk = 'Risk',
  Children = 'Children',
  Adolescence = 'Adolescence',
  Adult = 'Adult',
  Older = 'Older',
  Obese = 'Obese',
  Sedentary = 'Sedentary',
  Moderate = 'Moderate',
  Active = 'Active',
  UnderWeight = 'UnderWeight',
  Normal = 'Normal',
  OverWeight = 'OverWeight',
}
